### ISSUE TITLE
Question on Task 3

### ISSUE THREAD

**Issue by King32432** [sinyiwsy/arduino-tutorial#4]
Can I have more hints on task 3, I really don't know how to transfer and receive message using RX TX, where can I learn about the code? Besides, considering using the switches, is it the same as using a push button, using digitalRead to read true or false? Thx a lot!

**Comment by sinyiwsy** [comment]
1. I asked @umzr to upload a pair of sample code.
2. Yes, use digitalRead, but remember to use pull up/down.

**Comment by umzr** [comment]
******** This is the main Arduino ***********
#include <LiquidCrystal.h>



// initialize the library with the numbers of the interface pins
LiquidCrystal lcd(12, 11, 5, 4, 3, 2);
const int ledPin1 = 7;
const int ledPin2 = 8;

char mystr[10]; //Initialized variable to store recieved data

void setup() {
  Serial.begin(9600);
  lcd.begin(16, 2);
  // Print a message to the LCD.
  lcd.print("CUHK ROBOCON:");
}

void loop() {
 
  lcd.setCursor(0, 1);
  // print the number of seconds since reset:

  Serial.readBytes(mystr,7); //Read the serial data and store in var
   delay(100);
  
  lcd.print(mystr);
  
  Serial.println(mystr);
  delay(100);
}
 
******** This is the second Arduino ***********


char mystr[10] = "";
const int buttonPin2 = 2;     // the number of the pushbutton pin
const int buttonPin3 = 3;
const int buttonPin4 = 4;
const int ledPin =  13; 

int buttonState = 0; // variables will change:

void setup()
{
  Serial.begin(9600);
   // initialize the LED pin as an output:
  pinMode(ledPin, OUTPUT);
  // initialize the pushbutton pin as an input:
  pinMode(buttonPin2, INPUT);
  pinMode(buttonPin3, INPUT);
  pinMode(buttonPin4, INPUT);
}

void loop()
{
 

  

  
  buttonState = digitalRead(buttonPin2);
  if (buttonState == HIGH) {
    // turn LED on:
    digitalWrite(ledPin, HIGH);
  mystr[0] =  'F';
  mystr[1] =  'R';
  mystr[2] =  'O';
  mystr[3] =  'M';
  mystr[4] =  ' ';
  mystr[5] =  'B';
  mystr[6] =  ' ';
  mystr[7] =  ' ';
  Serial.write(mystr,7); //Write the serial data
	  delay(100);
  } else {
    // turn LED off:
    digitalWrite(ledPin, LOW);
  mystr[0] =  '2';
  mystr[1] =  '0';
  mystr[2] =  '2';
  mystr[3] =  '0';
  mystr[4] =  'E';
  mystr[5] =  'X';
  mystr[6] =  'E';
  mystr[7] =  ' ';
     delay(100);
    Serial.write(mystr,7);
     
  }
  

}

![image](https://user-images.githubusercontent.com/50727047/98196932-6e225f80-1f60-11eb-89cd-179731bf2838.png)

**Comment by sinyiwsy** [comment]
@umzr Your programming style... Umm 
Add Oil

**Comment by umzr** [comment]
> @umzr Your programming style... Umm 
> Add Oil

When i copy my code
GitHub auto deleted my space 😦

**Comment by sinyiwsy** [comment]
You can use ```.
